apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

images:
  - name: vmetrix/svc-calc
    newTag: local
  - name: vmetrix/svc-misc
    newTag: local
  - name: vmetrix/web-app
    newTag: local
