apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

images:
  - name: vmetrix/svc-calc
    newTag: c7ce570a89e1ae2ec0f4d61f458ca82b01b18da3  # svc-calc
  - name: vmetrix/svc-misc
    newTag: local  # svc-misc
  - name: vmetrix/web-app
    newTag: c7ce570a89e1ae2ec0f4d61f458ca82b01b18da3  # web-app
