apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

images:
  - name: vmetrix/svc-calc
    newTag: local  # svc-calc
  - name: vmetrix/svc-misc
    newTag: local  # svc-misc
  - name: vmetrix/web-app
    newTag: de046ecbcc04ab8f128d70cb8f7ffd2617e386aa  # web-app
