apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-calc
  labels:
    app: svc-calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-calc
  template:
    metadata:
      labels:
        app: svc-calc
    spec:
      containers:
        - name: svc-calc
          image: vmetrix/svc-calc:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
